#!/bin/bash
bsub -L /bin/bash -J FCC_25ns0001 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.0/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.0/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.0/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0002 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.1/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.1/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.1/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0003 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.2/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.2/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.2/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0004 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.3/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.3/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.3/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0005 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.4/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.4/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.4/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0006 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.5/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.5/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.5/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0007 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.6/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.6/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.6/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0008 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.7/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.7/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.7/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0009 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.8/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.8/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.8/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0010 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.9/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.9/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey1.9/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0011 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey2.0/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey2.0/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Dipole_25ns_50.00GeV_1e-04_R0.1_sey2.0/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0012 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.0/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.0/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.0/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0013 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.1/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.1/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.1/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0014 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.2/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.2/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.2/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0015 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.3/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.3/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.3/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0016 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.4/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.4/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.4/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0017 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.5/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.5/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.5/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0018 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.6/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.6/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.6/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0019 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.7/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.7/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.7/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0020 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.8/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.8/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.8/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0021 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.9/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.9/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey1.9/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0022 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey2.0/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey2.0/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Drift_25ns_50.00GeV_1e-04_R0.1_sey2.0/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0023 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.0/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.0/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.0/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0024 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.1/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.1/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.1/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0025 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.2/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.2/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.2/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0026 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.3/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.3/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.3/job.job
bjobs
bsub -L /bin/bash -J FCC_25ns0027 -o /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.4/STDOUT -e /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.4/STDERR -q 1nw < /afs/cern.ch/work/e/ebelli/workspace/FCChh/simulations/FCC_Quad_25ns_50.00GeV_1e-04_R0.1_sey1.4/job.job
bjobs
