#!/bin/bash
PYECLOUDPATH=/afs/cern.ch/user/j/jsopouse/Data/PyECLOUD/
PYPIC=/afs/cern.ch/user/j/jsopouse/Data/PyPIC/
CURRDIR=//afs/cern.ch/work/j/jsopouse/private/FromVacEnv2/MB.A8L1.B1CollisionB0SEY1.8
export CURRDIR
export PATH='/afs/cern.ch/user/p/pyhdtl/public/anaconda/bin':$PATH
export LD_LIBRARY_PATH='/afs/cern.ch/work/k/kli/public/local/lib':$LD_LIBRARY_PATH
export PYTHONPATH='/afs/cern.ch/user/p/pyhdtl/public/lib/':$PYTHONPATH
echo $PYTHONPATH
# Copy input and executable
mkdir PyECLOUD
mkdir PyPIC
cp -r ${PYECLOUDPATH}/* ./PyECLOUD/
cp -r ${PYPIC}/* ./PyPIC/
cp ${CURRDIR}/*.input .
cp ${CURRDIR}/*.beam .
cp ${CURRDIR}/*.mat .
cp ${CURRDIR}/*.py .
#execute beam generation
python run.py
#save result
cp Pyecltest.mat ${CURRDIR}
